/* Generated By:JavaCC: Do not edit this line. SoarParserConstants.java */
package com.soartech.soar.ide.core.model.ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SoarParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RARROW = 7;
  /** RegularExpression Id. */
  int SAME_TYPE = 8;
  /** RegularExpression Id. */
  int GEQUAL = 9;
  /** RegularExpression Id. */
  int LDISJUNCT = 10;
  /** RegularExpression Id. */
  int LEQUAL = 11;
  /** RegularExpression Id. */
  int NEQUAL = 12;
  /** RegularExpression Id. */
  int RDISJUNCT = 13;
  /** RegularExpression Id. */
  int AMPERSAND = 14;
  /** RegularExpression Id. */
  int ATSIGN = 15;
  /** RegularExpression Id. */
  int CARET = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int EMARK = 18;
  /** RegularExpression Id. */
  int EQUAL = 19;
  /** RegularExpression Id. */
  int GREATER = 20;
  /** RegularExpression Id. */
  int HYPHEN = 21;
  /** RegularExpression Id. */
  int LBRACE = 22;
  /** RegularExpression Id. */
  int LESS = 23;
  /** RegularExpression Id. */
  int LPAREN = 24;
  /** RegularExpression Id. */
  int PERIOD = 25;
  /** RegularExpression Id. */
  int PLUS = 26;
  /** RegularExpression Id. */
  int QMARK = 27;
  /** RegularExpression Id. */
  int RBRACE = 28;
  /** RegularExpression Id. */
  int RPAREN = 29;
  /** RegularExpression Id. */
  int TILDE = 30;
  /** RegularExpression Id. */
  int LSQBRACET = 31;
  /** RegularExpression Id. */
  int RSQBRACET = 32;
  /** RegularExpression Id. */
  int QUOTE = 33;
  /** RegularExpression Id. */
  int PRODTYPE = 34;
  /** RegularExpression Id. */
  int VARIABLE = 35;
  /** RegularExpression Id. */
  int INTEGER_CONST = 36;
  /** RegularExpression Id. */
  int SYMBOLIC_CONST = 37;
  /** RegularExpression Id. */
  int FLOATING_POINT_CONST = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"-->\"",
    "\"<=>\"",
    "\">=\"",
    "\"<<\"",
    "\"<=\"",
    "\"<>\"",
    "\">>\"",
    "\"&\"",
    "\"@\"",
    "\"^\"",
    "\",\"",
    "\"!\"",
    "\"=\"",
    "\">\"",
    "\"-\"",
    "\"{\"",
    "\"<\"",
    "\"(\"",
    "\".\"",
    "\"+\"",
    "\"?\"",
    "\"}\"",
    "\")\"",
    "\"~\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "<PRODTYPE>",
    "<VARIABLE>",
    "<INTEGER_CONST>",
    "<SYMBOLIC_CONST>",
    "<FLOATING_POINT_CONST>",
  };

}
